### ISSUE TITLE
Update to libthunarx-3

### ISSUE THREAD

**Issue by rauldipeas** [frederikmoellers/thunar-nextcloud-plugin#1]
Could you update this to use `libthunarx-3`?

**Comment by frederikmoellers** [comment]
I'll see what I can do. However, I've stopped using Thunar a while ago, so I can't test it continuously.

**Comment by schmidtja** [comment]
I looked at the new version of the thunar-archive-plugin and did a quick refactoring of the code for Thunarx3, see #2 .

Thanks for the plugin. :+1:
