### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by rasos** [frederikmoellers/thunar-nextcloud-plugin#3]
I would love to use nextcloud in thunar with XFCE.

However it seems some libraries are missing when compiling on Xubuntu 20.04: 

```
Package exo-2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `exo-2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'exo-2' found
Package thunarx-3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `thunarx-3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'thunarx-3' found
thunar-nextcloud-plugin.c:21:10: fatal error: exo/exo.h: Datei oder Verzeichnis nicht gefunden
   21 | #include <exo/exo.h>
      |          ^~~~~~~~~~~
compilation terminated.
tnp-provider.c:24:10: fatal error: libxfce4util/libxfce4util.h: Datei oder Verzeichnis nicht gefunden
   24 | #include <libxfce4util/libxfce4util.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Do I need to get the thunar source code first?

**Comment by frederikmoellers** [comment]
Hey there, sorry for leaving you hanging! I completely missed this issue and have only now seen it. Alas, I'm no longer using thunar and thus, the plugin, myself. So I can only offer very limited support.

Given that, it seems that you are "only" missing a few libraries. Let's hope they're still in the distribution (after all, this plugin is quite old). You should look for packages like `libthunar[something]-dev` and `libexo[something]-dev`. Those contain the necessary development (i.e. header) files to compile this plugin.

I guess (no guarantees!) that the packages you need to install are `libthunarx-3-dev` and either of `libexo-1-dev` or `libexo-2-dev`.

Hope this reply is not too late 😬

**Comment by frederikmoellers** [comment]
Closing in the hopes (and belief) that the issue has been resolved.
