### ISSUE TITLE
Thunar crash in FreeBSD after upgrade harfbuzz from 2.7.2 to 3.0.0

### ISSUE THREAD

**Issue by andrewhotlab** [frederikmoellers/thunar-nextcloud-plugin#4]
First of all: thank you so much for your work Frederick! This piece of code is precious for me in order to speed up daily work on my FreeBSD 12 and 13 desktops.

I just found the cause of a big issue I've been experiencing for a few days, when Thunar started to crash every time I right-click inside its window! :(
It looks like the issue come after the upgrade of the package [harfbuzz](https://www.freshports.org/print/harfbuzz) from the 2.7.2 to 3.0.0 version. Since I'm totally unable to even understand the code, can you be so kind to help me in understanding and solve the cause of this problem?

TIA

**Comment by andrewhotlab** [comment]
Sorry, just after I understood that the harfbuzz upgrade caused the issue, I solved the problem by reinstalling the following harfbuzz-dependent packages: `pango`, `librsvg2-rust`, `wx30-gtk3`, `libass`, `clutter`, `libraqm`. Now the plugin work again flawlessly! :)

**Comment by frederikmoellers** [comment]
Hey, thanks for the praise (and sorry for the late reply)!

To be honest, I don't really understand how those packages are related to this plugin. The only dependencies should be something like a `thunar`  and an `exo` library. Anyway, happy to hear that you apparently solved the problem 🙂
